server:
  port: "${service.context.port:8080}"
  servlet:
    context-path: "${service.context.path:/api}"
spring:
  application:
    name: "${service.name:app}"
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: ${service.datasource.url:jdbc:postgresql://localhost:5432/services}
    username: ${service.datasource.username:services}
    password: ${service.datasource.password:services}
  jpa:
    properties:
      hibernate:
        default_schema: ${service.datasource.schema:srv_auth}
        dialect: ${service.datasource.dialect:org.hibernate.dialect.PostgreSQL10Dialect}
        open-in-view: false
  data:
    jpa:
      repositories:
        enabled: true
  config:
    import: ${vault_configimport:}
  cloud:
    vault:
      uri: ${vault_uri:http://localhost:8200}
      authentication: ${vault_authentication:token}
      token: ${vault_token:00000000-0000-0000-0000-000000000000}
      app-role:
        role-id: ${vault_roleid}
        secret-id: ${vault_secretid}
      #Default
      enabled: ${vault_enabled:false}
      connection-timeout: ${vault_timeout:5000}
      read-timeout: ${vault_timeout:5000}
      fail-fast: ${vault_fastfail:true}

logging:
  level:
    root: INFO
  file:
    name: /tmp/app.log

management:
  endpoints:
    web:
      exposure:
        include: health

little-code:
  setup:
    auto-start: false
    database:
      auto-apply: false
      ddl:
        safe-drops: true
        auto-start: true
        auto-save: true

service:
  debug: true
  scope:
    name: auth-server
    setup:
      mode: AUTO
    admin:
      username: admin
      password: admin
  auth:
    mode: USERNAME
    redirect:
      uri: http://localhost
  config:
    path: /tmp/auth-server
    template:
      cert:
  context:
    port: 8080
    path: /api
  token:
    secret: 5403641c-16a1-4ef1-a816-7336106d96d9
    expires:
      days: 7
      minutes: 5
