server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: app
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: none
        default_schema:
        format_sql: false
        open-in-view: false
        show_sql: false
        use_sql_comments: false
  datasource:
    #driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username:
    password:

  config:
    import: ${vault_configimport:}
  cloud:
    vault:
      scheme: ${vault_schema:http}
      host: ${vault_host:}
      port: ${vault_port:80}
      authentication: ${vault_authentication:TOKEN}
      app-role:
        role-id: ${vault_app_role_role_id:services}
        secret-id: ${vault_app_role_secret_id:services}
      token: ${vault_token:00000000-0000-0000-0000-000000000000}
      enabled: ${vault_enabled:false}
      connection-timeout: ${vault_timeout:5000}
      read-timeout: ${vault_timeout:5000}
      fail-fast: ${vault_fastfail:true}
      kv:
        enabled: ${vault_enabled:true}
        backend: ${vault_kv_backend:}
        profile-separator: ${vault_kv_profile_separator:'/'}
        default-context: ${vault_kv_default_context:}

  security:
    user:
      name: services
      password: services

logging:
  level:
    root: INFO
    org:
      springframework: INFO
  file:
    name: /tmp/app.log



springdoc:
  swagger-ui:
    operationsSorter: method
    disable-swagger-default-url: true
    path: swagger-ui
  servers:
    dev: http://localhost:8080
    stg: http://localhost:8080
    prd: http://localhost:8080
  info:
    company: "Company"
    product: "Notify-Proxy"
    title: "Serviço de notificação"
    description: "Serviço de encaminhamento de notificações"
    version: "1.0.0"

littlecode:
  setup:
    auto-start: false
    database:
      auto-apply: false
      ddl:
        safe-drops: true
        auto-start: true
        auto-save: true

  mq:
    engine: com.littlecode.mq.adapter.Amqp
    auto-create: false
    auto-start: false
    stop-on-fail: true
    idle-sleep: 5000
    hostname: localhost
    v-hostname: /
    channel: 1
    exchange:
    port: 5672
    region: us-east-1
    name:
      consumer: event_notify
      dispatcher:
    max-number: 10
    client:
      id: services
      secret: services

app:
  config:
    webhook:
      uri: http://localhost:8080
      version: 0.0.0
      apiKey: 1234

