server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: app
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: none
        default_schema:
        format_sql: false
        open-in-view: false
        show_sql: false
        use_sql_comments: false
  datasource:
    #driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username:
    password:

  config:
    import:
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: token
      token: 00000000-0000-0000-0000-000000000000
      app-role:
        role-id:
        secret-id:
      enabled: false
      connection-timeout: 5000
      read-timeout: 5000
      fail-fast: true

logging:
  level:
    root: INFO
  file:
    name: /tmp/app.log

management:
  endpoints:
    web:
      exposure:
        include: health

service:
  debug: true
  scope:
    name: auth-server
    setup:
      mode: AUTO
    admin:
      username: admin
      password: admin
  auth:
    mode: USERNAME
    redirect:
      uri: http://localhost
  config:
    path: /tmp/auth-server
    template:
      cert:
  context:
    port: 8080
    path: /api
  token:
    secret: 5403641c-16a1-4ef1-a816-7336106d96d9
    expires:
      days: 7
      minutes: 5

springdoc:
  swagger-ui:
    operationsSorter: method
    disable-swagger-default-url: true
    path: swagger-ui
  servers:
    dev: http://localhost:8080
    stg: http://localhost:8080
    prd: http://localhost:8080
  info:
    company: "Company"
    product: "Auth"
    title: "AuthServer"
    description: "API authorization"
    version: "1.0.0"

littlecode:
  setup:
    auto-start: false
    database:
      auto-apply: false
      ddl:
        safe-drops: true
        auto-start: true
        auto-save: true
